### ISSUE TITLE
RStudio add-in version

### ISSUE THREAD

**Issue by larmarange** [ewenharrison/shinyfit#1]
Hi,

do you have any plan for releasing a RStudio add-in version of shinyfit, that could be used locally by a user to explorer his own dataset?

It would be a great tool for students not very familiar with coding.

Best regards

**Comment by ewenharrison** [comment]
Thanks for your interest. 
It can be run from RStudio directly as it is a ShinyApp. 
Just by opening `app.R` and hitting the Run App button.
